name: Welcome
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/welcome-action@v1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          FIRST_ISSUE: >
            👋 @${author}
            Congrats on creating your first Issue in the C0D1NG Organization! 🎉

          FIRST_PR: >
            👋 @${author}
            Congrats on making your first Pull Request in the C0D1NG Organization! 🥳
